Enable pruning by default.  Fix the test cases to run with and without pruning but only compare against the expected results when not pruned.

diff --git a/trunk/src/test/Makefile b/trunk/src/test/Makefile
--- a/trunk/src/test/Makefile
+++ b/trunk/src/test/Makefile
@@ -2,7 +2,7 @@
 #
 # Part of the Routino routing software.
 #
-# This file Copyright 2011 Andrew M. Bishop
+# This file Copyright 2011-2012 Andrew M. Bishop
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -43,16 +43,14 @@ exe :
 
 test : exe
 	@status=true ;\
-	[ -d fat ] || mkdir fat ;\
 	for script in $(S); do \
 	   echo "" ;\
-	   echo "Testing: $$script (non-slim) ... " ;\
+	   echo "Testing: $$script (non-slim, no pruning) ... " ;\
 	   if ./$$script fat; then echo "... passed"; else echo "... FAILED"; status=false; fi ;\
 	done ;\
-	[ -d slim ] || mkdir slim ;\
 	for script in $(S); do \
 	   echo "" ;\
-	   echo "Testing: $$script (slim) ... " ;\
+	   echo "Testing: $$script (slimm, no pruning) ... " ;\
 	   if ./$$script slim; then echo "... passed"; else echo "... FAILED"; status=false; fi ;\
 	done ;\
 	echo "" ;\
@@ -63,13 +61,33 @@ test : exe
 	if diff -q -r slim fat; then echo "... matched"; else echo "... match FAILED"; status=false; fi ;\
 	echo "" ;\
 	if $$status; then echo "Success: slim and non-slim results match"; else echo "Warning: slim and non-slim results are different - FAILED"; fi ;\
+	for script in $(S); do \
+	   echo "" ;\
+	   echo "Testing: $$script (non-slim, pruning) ... " ;\
+	   if ./$$script fat prune; then echo "... passed"; else echo "... FAILED"; status=false; fi ;\
+	done ;\
+	for script in $(S); do \
+	   echo "" ;\
+	   echo "Testing: $$script (slim, pruning) ... " ;\
+	   if ./$$script slim prune; then echo "... passed"; else echo "... FAILED"; status=false; fi ;\
+	done ;\
+	echo "" ;\
+	if $$status; then echo "Success: all tests passed"; else echo "Warning: Some tests FAILED"; fi ;\
+	$$status || exit 1 ;\
+	echo "" ;\
+	echo "Comparing: slim and non-slim results ... " ;\
+	if diff -q -r slim-pruned fat-pruned; then echo "... matched"; else echo "... match FAILED"; status=false; fi ;\
+	echo "" ;\
+	if $$status; then echo "Success: slim and non-slim results match"; else echo "Warning: slim and non-slim results are different - FAILED"; fi ;\
 	$$status
 
 ########
 
 clean:
-	rm -rf slim
 	rm -rf fat
+	rm -rf slim
+	rm -rf fat-pruned
+	rm -rf slim-pruned
 	rm -f *.log
 	rm -f core
 	rm -f *~
